# Generated by Django 3.1.7 on 2021-04-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('yom', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('engine_no', models.CharField(max_length=100)),
                ('chassis_number', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs', models.IntegerField()),
                ('cif_cost', models.IntegerField()),
                ('delivery_order', models.IntegerField()),
                ('radiation', models.IntegerField()),
                ('ntsa_sticker', models.IntegerField()),
                ('insurance', models.IntegerField()),
                ('cfs_chgs', models.IntegerField()),
                ('agency', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.car')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.car')),
                ('total_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.cost')),
            ],
        ),
    ]
