# Generated by Django 3.1.7 on 2021-04-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20210403_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='total_cost',
        ),
    ]
