# Generated by Django 3.1.7 on 2021-04-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_remove_cost_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='car',
            new_name='chassis_number',
        ),
    ]
