# Generated by Django 3.1.7 on 2021-04-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20210405_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='chassis_number',
            new_name='car',
        ),
    ]
