# Generated by Django 3.1.7 on 2021-04-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20210405_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='others',
            field=models.IntegerField(default=0),
        ),
    ]
